[package]
name = "tuggerah"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
byteorder = "1.5.0"
env_logger = "0.11.6"
log = "0.4.25"
serde = { version="1.0.217", features = ["derive"]}
sqlite = "0.36.1"
uuid = { version="1.12.1", features = ["v4"]}
